import { type ProductPaginatedResponse } from "./product.responses";

export const mockProductPaginatedResponse: ProductPaginatedResponse = {
  data: [
    {
      id: 1,
      name: "iPhone 15 Pro",
      summary: "Flagship smartphone with advanced features",
      content:
        "The latest iPhone with A17 Pro chip, improved camera system, and titanium design.",
      status: "active",
      created_at: "2024-01-15T10:30:00Z",
      updated_at: "2024-12-18T14:20:00Z",
      brand: {
        id: 1,
        name: "Apple",
      },
      images: [
        {
          id: 101,
          src: "https://bizweb.dktcdn.net/100/624/127/products/7688be9e-ec9e-4bc5-92a6-e88e107a7610.jpg?v=1765786434910",
          alt: "iPhone 15 Pro Front View",
          position: 1,
          filename: "iphone15-pro-1.jpg",
          size: 2048576,
          width: 1200,
          height: 1200,
        },
        {
          id: 102,
          src: "https://example.com/images/iphone15-pro-2.jpg",
          alt: "iPhone 15 Pro Back View",
          position: 2,
          filename: "iphone15-pro-2.jpg",
          size: 1897349,
          width: 1200,
          height: 1200,
        },
      ],
      variants: [
        {
          id: 201,
          sku: "SKU-IP15-BK-128",
          barcode: "1234567890128",
          price: 999,
          compare_at_price: 1099,
          title: "Black 128GB",
          option1: "Black",
          option2: "128GB",
          option3: "",
          taxable: true,
          inventory_quantity: 50,
          unit: "piece",
          image: {
            id: 101,
            src: "https://bizweb.dktcdn.net/100/624/127/products/7688be9e-ec9e-4bc5-92a6-e88e107a7610.jpg?v=1765786434910",
            alt: "iPhone 15 Pro Black",
            position: 1,
            filename: "iphone15-pro-1.jpg",
            size: 2048576,
            width: 1200,
            height: 1200,
          },
          position: 1,
        },
        {
          id: 202,
          sku: "SKU-IP15-SL-256",
          barcode: "1234567890256",
          price: 1099,
          compare_at_price: 1199,
          title: "Silver 256GB",
          option1: "Silver",
          option2: "256GB",
          option3: "",
          taxable: true,
          inventory_quantity: 35,
          unit: "piece",
          image: {
            id: 102,
            src: "https://example.com/images/iphone15-pro-2.jpg",
            alt: "iPhone 15 Pro Silver",
            position: 2,
            filename: "iphone15-pro-2.jpg",
            size: 1897349,
            width: 1200,
            height: 1200,
          },
          position: 2,
        },
      ],
      options: [
        {
          id: 301,
          name: "Color",
          position: 1,
          values: [
            { id: 3001, value: "Black" },
            { id: 3002, value: "Silver" },
            { id: 3003, value: "Gold" },
          ],
        },
        {
          id: 302,
          name: "Storage",
          position: 2,
          values: [
            { id: 3004, value: "128GB" },
            { id: 3005, value: "256GB" },
            { id: 3006, value: "512GB" },
          ],
        },
      ],
      types: [
        { id: 401, name: "Electronics" },
        { id: 402, name: "Smartphones" },
        { id: 403, name: "Siuuu" },
      ],
    },
    {
      id: 2,
      name: "Samsung Galaxy S24",
      summary: "Premium Android smartphone with Galaxy AI",
      content:
        "Experience the future with Galaxy S24 featuring advanced AI capabilities and stunning display.",
      status: "active",
      created_at: "2024-02-20T09:15:00Z",
      updated_at: "2024-12-10T11:45:00Z",
      brand: {
        id: 2,
        name: "Samsung",
      },
      images: [
        {
          id: 103,
          src: "https://res.cloudinary.com/dgbmaul7r/image/upload/v1766031050/dog_20251218111049_8d4a02b7.jpg",
          alt: "Samsung Galaxy S24 Front",
          position: 1,
          filename: "galaxy-s24-1.jpg",
          size: 1756383,
          width: 1200,
          height: 1200,
        },
      ],
      variants: [
        {
          id: 203,
          sku: "SKU-GS24-PH-256",
          barcode: "9876543210256",
          price: 899,
          compare_at_price: 999,
          title: "Phantom 256GB",
          option1: "Phantom Black",
          option2: "256GB",
          option3: "",
          taxable: true,
          inventory_quantity: 42,
          unit: "piece",
          image: {
            id: 103,
            src: "https://example.com/images/galaxy-s24-1.jpg",
            alt: "Samsung Galaxy S24",
            position: 1,
            filename: "galaxy-s24-1.jpg",
            size: 1756383,
            width: 1200,
            height: 1200,
          },
          position: 1,
        },
      ],
      options: [
        {
          id: 303,
          name: "Color",
          position: 1,
          values: [
            { id: 3007, value: "Phantom Black" },
            { id: 3008, value: "Onyx" },
          ],
        },
      ],
      types: [
        { id: 401, name: "Electronics" },
        { id: 402, name: "Smartphones" },
      ],
    },
    {
      id: 3,
      name: "iPad Air",
      summary: "Versatile tablet for work and entertainment",
      content:
        "Powerful and colorful iPad Air with M1 chip for productivity and creativity.",
      status: "active",
      created_at: "2024-03-10T14:00:00Z",
      updated_at: "2024-12-12T16:30:00Z",
      brand: {
        id: 1,
        name: "Apple",
      },
      images: [
        {
          id: 104,
          src: "https://example.com/images/ipad-air-1.jpg",
          alt: "iPad Air Space Gray",
          position: 1,
          filename: "ipad-air-1.jpg",
          size: 2359296,
          width: 1200,
          height: 1200,
        },
      ],
      variants: [
        {
          id: 204,
          sku: "SKU-IPAD-SG-64",
          barcode: "1111111111111",
          price: 599,
          compare_at_price: 699,
          title: "Space Gray 64GB",
          option1: "Space Gray",
          option2: "64GB",
          option3: "WiFi",
          taxable: true,
          inventory_quantity: 28,
          unit: "piece",
          image: {
            id: 104,
            src: "https://example.com/images/ipad-air-1.jpg",
            alt: "iPad Air",
            position: 1,
            filename: "ipad-air-1.jpg",
            size: 2359296,
            width: 1200,
            height: 1200,
          },
          position: 1,
        },
      ],
      options: [
        {
          id: 304,
          name: "Color",
          position: 1,
          values: [
            { id: 3009, value: "Space Gray" },
            { id: 3010, value: "Silver" },
          ],
        },
        {
          id: 305,
          name: "Storage",
          position: 2,
          values: [
            { id: 3011, value: "64GB" },
            { id: 3012, value: "256GB" },
          ],
        },
      ],
      types: [
        { id: 401, name: "Electronics" },
        { id: 403, name: "Tablets" },
      ],
    },
  ],
  currentPage: 1,
  pageSize: 10,
  totalPages: 5,
  totalElements: 48,
  hasNext: false,
  hasPrevious: false,
};
